# This workflow will build a Java project with Ant

name: build

on:
  workflow_dispatch:
  push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
      
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      
    - name: Build with Ant
      run: |
        ant
        
    - name: Check status
      run: |
        set | sort
        echo -n "Current directory: "
        pwd
        find | sort

    - uses: actions/upload-artifact@v3
      with:
        name: blackboard-generic
        path: install/*

